#!/usr/bin/env bash
# Wrapper around docker-compose for this project

script="$(basename "$0")"
symlink="$USER_BIN/$script"

if [[ ! -L "$symlink" ]]; then
    ln -snf "$SCRIPT_DIR/$script" "$USER_BIN" && {
        echo "Symlink created at $symlink"
        exit 0
    }
fi

docker-compose -f "$SCRIPT_DIR/docker-compose.yml" --env-file "$SCRIPT_DIR/.env" "$@"
