#!/usr/bin/env bash
# Manage helper scripts installation

VERSION="1.2.0"

setenv() {
    local runuser homedir
    if [[ $1 == "root" ]]; then
        runuser="root"
        homedir="/root"
    else
        runuser="${SUDO_USER:-$USER}"
        homedir="$(eval echo "~$runuser")"
    fi

    export USER="$runuser"
    local bindir="$homedir/bin"
    local bashrc="$homedir/.bashrc"
    local scriptpath="$(readlink -f "$0")"
    local scriptdir="$(dirname "$scriptpath")"

    mkdir -p "$bindir"
    chmod -R +x "$bindir"
    chown -R "$runuser":"$runuser" "$bindir"
    ln -snf "$scriptpath" "$bindir/$(basename "$0")"

    {
        echo "export PATH=\"$PATH:$bindir\""
        echo "export SCRIPT_DIR=\"$scriptdir\""
        echo "export SCRIPT_PATH=\"$scriptpath\""
        echo "export SETENV_SET=true"
        echo "export BASHRC_FILE=\"$bashrc\""
        echo "export USER_BIN=\"$bindir\""
        echo "export SETENV_VERSION=\"$VERSION\""
    } >> "$bashrc"
    source "$bashrc"
}

if [[ "$SETENV_SET" != "true" ]]; then
    echo "Setup setenv started"
    setenv "$1"
    exit 0
else
    echo "'$0' already installed"
    exit 0
fi
