#!/usr/bin/env bash
# Execute a command inside the ansible container

script="$(basename "$0")"
symlink="$USER_BIN/$script"

if [[ ! -L "$symlink" ]]; then
    ln -snf "$SCRIPT_DIR/.helpers/$script" "$USER_BIN" && {
        echo "Symlink created at $symlink"
        exit 0
    }
fi

docker-stack exec ansible /bin/bash "$@"
