#!/usr/bin/env bash
# Restart ansible container after switching the role

script="$(basename "$0")"
symlink="$USER_BIN/$script"

if [[ ! -L "$symlink" ]]; then
    ln -snf "$SCRIPT_DIR/.helpers/$script" "$USER_BIN" && {
        echo "Symlink created at $symlink"
        exit 0
    }
fi

role="$1"
if [[ -n "$role" ]]; then
    ansible-role "$role"
else
    echo "Usage: $script <role>" >&2
    exit 1
fi

docker-stack kill ansible
docker-stack rm -f ansible
docker-stack up -d ansible
