#!/usr/bin/env bash
# Switch ansible role and install dependencies

script="$(basename "$0")"
symlink="$USER_BIN/$script"

if [[ ! -L "$symlink" ]]; then
    ln -snf "$SCRIPT_DIR/.helpers/$script" "$USER_BIN" && {
        echo "Symlink created at $symlink"
        exit 0
    }
fi

role="$1"
if [[ -z "$role" ]]; then
    echo "Usage: $script <role>" >&2
    exit 1
fi

env_file="$SCRIPT_DIR/.env"
sed -i -e "s/^ANSIBLE_ROLE=.*/ANSIBLE_ROLE=$role/" "$env_file"

if [[ -d "$SCRIPT_DIR/ansible/$role" ]]; then
    cd "$SCRIPT_DIR/ansible/$role" && ansible-galaxy install -r requirements.yml
fi
